import json

def search(data, search):
    return [element for element in data if element['category'] == search]

def styleanda(file):
    f = open(file)
    data = json.load(f)
    length = len(data)
    print(length)
    length_outwear = len(search(data, "outwear"))
    print(length_outwear)
    length_skirt = len(search(data, "skirt"))
    print(length_skirt)
    length_dress = len(search(data, "dress"))
    print(length_dress)
    length_shorts = len(search(data, "shorts"))
    print(length_shorts)
    length_trousers = len(search(data, "trousers"))
    print(length_trousers)
    length_shirt = len(search(data, "shirt"))
    print(length_shirt)
    length_jacket = len(search(data, "jacket"))
    print(length_jacket)
    f.close()
    
def farfetch(file):
    f = open(file)
    data = json.load(f)
    length = len(data)
    print(length)
    length_coats = len(search(data, "Coats"))
    print(length_coats)
    length_jackets = len(search(data, "Jackets"))
    print(length_jackets)
    length_shirts = len(search(data, "Shirts"))
    print(length_shirts)
    length_shorts = len(search(data, "Shorts"))
    print(length_shorts)
    length_pants = len(search(data, "Pants"))
    print(length_pants)
    length_tshirt = len(search(data, "T-Shirts & Vests"))
    print(length_tshirt)
    length_sweater = len(search(data, "Sweatshirts & Knitwear"))
    print(length_sweater)
    length_polo = len(search(data, "Polo Shirts"))
    print(length_polo)
    length_skirts = len(search(data, "Skirts"))
    print(length_skirts)
    length_dresses = len(search(data, "Dresses"))
    print(length_dresses)
    f.close()
    
def yoox(file):
    f = open(file)
    data = json.load(f)
    length = len(data)
    print(length)
    length_coats = len(search(data, "Coats & Jackets"))
    print(length_coats)
    length_shorts = len(search(data, "Shorts & Bermuda"))
    print(length_shorts)
    length_pants = len(search(data, "Pants"))
    print(length_pants)
    length_shirts = len(search(data, "Shirts"))
    print(length_shirts)
    length_tshirt = len(search(data, "T-Shirts and Tops"))
    print(length_tshirt)
    length_skirts = len(search(data, "Skirts"))
    print(length_skirts)
    length_dresses = len(search(data, "Dresses"))
    print(length_dresses)
    length_hooded = len(search(data, "Hooded sweatshirts"))
    print(length_hooded)
    f.close()
    
def darveys(file):
    f = open(file)
    data = json.load(f)
    length = len(data)
    print(length)
    length_coats = len(search(data, "Sweatshirts & hoodies"))
    print(length_coats)
    length_shorts = len(search(data, "Jackets"))
    print(length_shorts)
    length_pants = len(search(data, "Jeans"))
    print(length_pants)
    length_shirts = len(search(data, "Sweaters & knitwear"))
    print(length_shirts)
    length_tshirt = len(search(data, "Pants"))
    print(length_tshirt)
    length_skirts = len(search(data, "Polos"))
    print(length_skirts)
    length_dresses = len(search(data, "Shirts"))
    print(length_dresses)
    length_hooded = len(search(data, "Shorts"))
    print(length_hooded)
    length_9 = len(search(data, "T-shirts"))
    print(length_9)
    length_10 = len(search(data, "Trench coats"))
    print(length_10)
    length_11 = len(search(data, "Dresses"))
    print(length_11)
    length_12 = len(search(data, "Skirts"))
    print(length_12)
    length_13 = len(search(data, "Tops"))
    print(length_13)
    f.close()
    
def boozt(file):
    f = open(file)
    data = json.load(f)
    length = len(data)
    print(length)
    length_coats = len(search(data, "jeans"))
    print(length_coats)
    length_shorts = len(search(data, "outwear"))
    print(length_shorts)
    length_pants = len(search(data, "poloshirts"))
    print(length_pants)
    length_shirts = len(search(data, "shirts"))
    print(length_shirts)
    length_tshirt = len(search(data, "shorts"))
    print(length_tshirt)
    length_skirts = len(search(data, "trousers"))
    print(length_skirts)
    length_dresses = len(search(data, "dress"))
    print(length_dresses)
    length_hooded = len(search(data, "jacket"))
    print(length_hooded)
    length_9 = len(search(data, "jean"))
    print(length_9)
    length_10 = len(search(data, "skirts"))
    print(length_10)
    f.close()

def sum(file):
    f = open(file)
    data = json.load(f)
    length = len(data)
    print(length)
    length_coats = len(search(data, "trouser"))
    print(length_coats)
    length_shorts = len(search(data, "outwear"))
    print(length_shorts)
    length_pants = len(search(data, "shirt"))
    print(length_pants)
    length_shirts = len(search(data, "short"))
    print(length_shirts)
    length_tshirt = len(search(data, "dress"))
    print(length_tshirt)
    length_skirts = len(search(data, "skirt"))
    print(length_skirts)
    f.close()
    
print('---------------------')
styleanda('file_storage/final_dataset/stylenanda_data.json')
farfetch('file_storage/final_dataset/farfetch_data.json')
yoox('file_storage/final_dataset/yoox_data.json')
darveys('file_storage/final_dataset/darveys_data.json')
boozt('file_storage/final_dataset/boozt_data.json')

sum('summary1.json')
